module.exports = async () => {
	const assert = require('assert');
	const { Lock, delay } = require('..');
	const lock = new Lock();
	let value = 1;
	lock.promise.then(() => value++);
	await delay(0);
	assert(value === 2);
	const lock2 = lock.lock();
	lock.promise.then(() => value++);
	await delay(0);
	assert(value === 2);
	await lock2.unlock();
	assert(value === 3);
	const lock4 = lock2.lock();
	const lock5 = lock2.lock();
	lock.promise.then(() => value++);
	const lock6_p = lock.wait_and_lock();
	lock.promise.then(() => value++);
	await delay(0);
	assert(value === 3);
	await lock5.unlock();
	assert(value === 3);
	await lock4.unlock();
	assert(value === 4);
	const lock6 = await lock6_p;
	assert(value === 4);
	await lock6.unlock();
	assert(value === 5);
};
